# --- Experiment configurations --------------------------------------------------------------------

# experiment name, used as folder name
experiment_name: camels_cl_253_basins_finetuned

# files to specify training, validation and test basins (relative to code root or absolute path)
train_basin_file: configs/camels-cl/camels_cl_basin_253.txt 
validation_basin_file: configs/camels-cl/camels_cl_basin_253.txt 
test_basin_file: configs/camels-cl/camels_cl_basin_253.txt

# --- Training configuration -----------------------------------------------------------------------

# specify learning rates to use starting at specific epochs (0 is the initial learning rate)
learning_rate:
    0: 5e-4
    2: 5e-5	

# Number of training epochs
epochs: 10

# TODO: This will need to change for each model
finetune_modules:
- head
- lstm


