# --- Experiment configurations --------------------------------------------------------------------

# experiment name, used as folder name
experiment_name: cudalstm_camels_cl_253_basins

# place to store run directory (if empty runs are stored in $cwd$/runs/)
run_dir:

# files to specify training, validation and test basins (relative to code root or absolute path)
train_basin_file: configs/camels-cl/camels_cl_basin_253.txt
validation_basin_file: configs/camels-cl/camels_cl_basin_253.txt
test_basin_file: configs/camels-cl/camels_cl_basin_253.txt

# training, validation and test time periods (format = 'dd/mm/yyyy')
train_start_date: '01/10/1999'
train_end_date: '30/09/2000'
validation_start_date: '01/10/1988'
validation_end_date: '30/09/1989'
test_start_date: '01/10/1989'
test_end_date: '30/09/1999'

# fixed seed, leave empty to use a random seed
seed: 

# which GPU (id) to use [in format of cuda:0, cuda:1 etc, or cpu or None]
device: cuda:0

# --- Validation configuration ---------------------------------------------------------------------

# specify after how many epochs to perform validation
validate_every: 1

# specify how many random basins to use for validation
validate_n_random_basins: 253

# specify which metrics to calculate during validation (see codebase.evaluation.metrics)
metrics:
- NSE
- KGE
- Alpha-NSE
- Beta-NSE

# --- Model configuration --------------------------------------------------------------------------

# base model type [lstm, ealstm, cudalstm, embcudalstm, shortcutlstm, dropoutlstm, cudalstminitialh]
# (has to match the if statement in modelzoo/__init__.py)
model: gru

# prediction head [regression, mdn, umal]. Define the head specific parameters below
head: regression

# ----> Embedding network settings <----

# define embedding network for static inputs
statics_embedding:
  type: fc
  # define number of neurons per layer in the FC network used as embedding network
  hiddens:
    - 30
    - 20
    - 64
  # activation function of embedding network
  activation: tanh
  # dropout applied to embedding network
  dropout: 0.0

# define embedding network for dynamic inputs
dynamics_embedding:
  type: fc
  # define number of neurons per layer in the FC network used as embedding network
  hiddens:
    - 30
    - 20
    - 64
  # activation function of embedding network
  activation: tanh
  # dropout applied to embedding network
  dropout: 0.0

# ----> General settings <----

# Number of cell states of the LSTM
hidden_size: 128

# Initial bias value of the forget gate
initial_forget_bias: 3

# Dropout applied to the output of the LSTM
output_dropout: 0.4

output_activation: linear

# --- Training configuration -----------------------------------------------------------------------

# specify optimizer [Adam, Adadelta]
optimizer: Adam

# specify loss [MSE, NSE, RMSE, UMALLoss, MDNLoss]
loss: NSE

# specify learning rates to use starting at specific epochs (0 is the initial learning rate)
learning_rate:
    0: 1e-3
    1: 5e-4

# Mini-batch size
batch_size: 256

# Number of training epochs
epochs: 5

# If True, clips norm of gradients
clip_gradient_norm: 1

# Defines which time steps are used to calculate the loss. Can't be larger than seq_length
predict_last_n: 1

# Length of the input sequence
seq_length: 365

# Number of parallel workers used in the data_dir pipeline
num_workers: 8

# Log the training loss every n steps
log_interval: 5

# If true, writes logging results into tensorboard file
log_tensorboard: True

# Save model weights every n epochs
save_weights_every: 1

# Store the results of the validation to disk
save_validation_results: True

# --- Data configurations --------------------------------------------------------------------------

dataset: camels_cl

# Path to CAMELS data_dir set
data_dir: data_dir

# Forcing product [daymet, maurer, maurer_extended, nldas, nldas_extended, chile_forcings]
# can be either a list of forcings or a single forcing product
forcings:
- chile_forcings

# variables to use as time series input (names match the data_dir file column headers)
# Note: In case of multiple input forcing products, you have to append the forcing product behind
# each variable. E.g. 'prcp(mm/day)' of the daymet product is 'prcp(mm/day)_daymet'
dynamic_inputs:
- PRCP(mm/day)
- SRAD(W/m2)
- Tmax(C)
- Tmin(C)
- Vp(Pa)

# which columns to use as target
target_variables:
- QObs(mm/d)

static_attributes:
- elev_mean
- slope_mean
- area_gages2
- lai_max
- lai_diff
- gvf_max
- gvf_diff
- p_mean
- pet_mean
- aridity
- high_prec_freq
- high_prec_dur
- low_prec_freq
- low_prec_dur
